# Generated by Django 3.0.3 on 2020-08-21 10:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_point', to='restful_server.PointModel')),
                ('to_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_point', to='restful_server.PointModel')),
            ],
        ),
    ]
